name: "Send CI failure slack message"
description: "Send slack message on failed CI run"
author: "Tore Hagen"

inputs:
  slack_url:
    description: "Slack webhook URL"
    required: true
  github_token:
    description: GitHub token for API access
    required: true

runs:
  using: "composite"
  steps:
    - name: Set short SHA
      id: short_sha
      shell: bash
      run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    - name: Get failed jobs
      id: failed_jobs
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        job_data=$(gh api repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/jobs)
        
        # Find both: completed failed jobs AND in-progress jobs with failed steps
        failed_info=$(echo "$job_data" | jq -r '
          .jobs[] | 
          select(
            (.conclusion == "failure") or 
            (.status == "in_progress" and ([.steps[]? | select(.conclusion == "failure")] | length > 0))
          ) | 
          if .conclusion == "failure" then
            "- <https://github.com/'${GITHUB_REPOSITORY}'/actions/runs/'${GITHUB_RUN_ID}'/job/\(.id)|\(.name)>"
          else
            ([.steps[]? | select(.conclusion == "failure") | 
              "  - Step: \(.name)"
            ] | join("\n")) as $steps |
            "- <https://github.com/'${GITHUB_REPOSITORY}'/actions/runs/'${GITHUB_RUN_ID}'/job/\(.id)|\(.name)> (in progress)\n\($steps)"
          end
        ')
        
        echo "jobs<<EOF" >> $GITHUB_OUTPUT
        echo "$jobs" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Slack Notification on Failure
      uses: kosli-dev/reusable-actions/.github/actions/send-slack-message@main
      with:
        slack_url: ${{ inputs.slack_url }}
        plain_text_preview: ${{ github.workflow }} faild in ${GITHUB_REPOSITORY}
        message: |
          <https://github.com/${GITHUB_REPOSITORY}|${GITHUB_REPOSITORY}> failed in *${{ github.workflow }}* <https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}|${{ steps.short_sha.outputs.sha }}>
          <https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}|Failed workflow action>
          Failed jobs:
          ${{ steps.failed_jobs.outputs.jobs }}
